import { useQuery } from '@tanstack/react-query';
import axios from 'axios';

import { extractVideoId } from '@/lib/youtube';

interface SubtitleLanguage {
  languageCode: string;
  languageName: string;
  isTranslatable: boolean;
  isAutoGenerated: boolean;
}

interface VideoInfo {
  videoId: string;
  title: string;
  duration: number;
  viewCount: number;
  channelName: string;
}

interface SubtitleData {
  index: number;
  startTime: number;
  endTime: number;
  text: string;
}

interface SubtitlesResponse {
  video: VideoInfo;
  languages: SubtitleLanguage[];
  subtitles: Record<string, SubtitleData[]>;
  message?: string;
  error?: string;
}

/**
 * 자막 정보를 가져오는 함수
 */
async function fetchSubtitles(videoId: string): Promise<SubtitlesResponse> {
  const validVideoId = extractVideoId(videoId);
  if (!validVideoId) {
    throw new Error('유효하지 않은 YouTube Video ID입니다');
  }

  const { data } = await axios.get<SubtitlesResponse>('/api/subtitles', {
    params: {
      videoId: validVideoId,
    },
  });

  return data;
}

/**
 * YouTube 자막 정보를 가져오는 React Query 훅
 */
export function useSubtitles(videoId: string | null) {
  return useQuery({
    queryKey: ['subtitles', videoId],
    queryFn: () => fetchSubtitles(videoId!),
    enabled: !!videoId,
    staleTime: 5 * 60 * 1000, // 5분
    retry: 1,
  });
}

export type { SubtitleData, SubtitleLanguage, SubtitlesResponse, VideoInfo };
