import { NextRequest, NextResponse } from "next/server";
import { Innertube } from "youtubei.js";
import { extractVideoId } from "@/lib/youtube";

/**
 * GET /api/subtitles?videoId={id}
 * YouTube 비디오의 자막 정보를 가져옵니다
 */
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const videoId = searchParams.get("videoId");

    if (!videoId) {
      return NextResponse.json(
        { error: "videoId가 필요합니다" },
        { status: 400 }
      );
    }

    // Video ID 검증
    const validVideoId = extractVideoId(videoId);
    if (!validVideoId) {
      return NextResponse.json(
        { error: "유효하지 않은 YouTube Video ID입니다" },
        { status: 400 }
      );
    }

    // YouTube Innertube 인스턴스 생성
    const youtube = await Innertube.create();

    // 비디오 정보 가져오기
    const videoInfo = await youtube.getInfo(validVideoId);

    // 자막 트랙 정보 추출
    const captions = videoInfo.captions?.caption_tracks || [];

    // 자막 언어 목록 생성
    const languages = captions.map((caption) => {
      const name = caption.name;
      const languageName =
        typeof name === "string"
          ? name
          : name && typeof name === "object" && "simple_text" in name
          ? (name as { simple_text: string }).simple_text
          : caption.language_code;

      return {
        languageCode: caption.language_code,
        languageName,
        isTranslatable: caption.is_translatable || false,
        isAutoGenerated: caption.kind === "asr",
        baseUrl: caption.base_url,
      };
    });

    // 비디오 기본 정보
    const basicInfo = videoInfo.basic_info;
    const duration =
      basicInfo?.duration && typeof basicInfo.duration === "object"
        ? (basicInfo.duration as { seconds: number }).seconds || 0
        : typeof basicInfo?.duration === "number"
        ? basicInfo.duration
        : 0;

    const videoDetails = {
      videoId: validVideoId,
      title: basicInfo?.title || "제목 없음",
      duration,
      viewCount: basicInfo?.view_count || 0,
      channelName: basicInfo?.author || "알 수 없음",
    };

    return NextResponse.json({
      success: true,
      video: videoDetails,
      languages,
      totalLanguages: languages.length,
    });
  } catch (error) {
    console.error("자막 정보 가져오기 실패:", error);
    return NextResponse.json(
      {
        error: "자막 정보를 가져오는 중 오류가 발생했습니다",
        details: error instanceof Error ? error.message : "알 수 없는 오류",
      },
      { status: 500 }
    );
  }
}
