"use client";

import { useState } from "react";
import { extractVideoId, isValidYouTubeUrl } from "@/lib/youtube";

interface SubtitleLanguage {
  languageCode: string;
  languageName: string;
  isTranslatable: boolean;
  isAutoGenerated: boolean;
}

interface VideoInfo {
  videoId: string;
  title: string;
  duration: number;
  viewCount: number;
  channelName: string;
}

interface SubtitleData {
  index: number;
  startTime: number;
  endTime: number;
  text: string;
}

export default function Home() {
  const [url, setUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [videoInfo, setVideoInfo] = useState<VideoInfo | null>(null);
  const [languages, setLanguages] = useState<SubtitleLanguage[]>([]);
  const [selectedLanguage, setSelectedLanguage] = useState<string | null>(null);
  const [subtitlesByLanguage, setSubtitlesByLanguage] = useState<
    Record<string, SubtitleData[]>
  >({});

  const handleLoadSubtitles = async () => {
    if (!url.trim()) {
      setError("YouTube URL을 입력해주세요");
      return;
    }

    if (!isValidYouTubeUrl(url)) {
      setError("유효하지 않은 YouTube URL입니다");
      return;
    }

    setLoading(true);
    setError(null);
    setVideoInfo(null);
    setLanguages([]);
    setSubtitlesByLanguage({});
    setSelectedLanguage(null);

    try {
      const videoId = extractVideoId(url);
      if (!videoId) {
        throw new Error("Video ID를 추출할 수 없습니다");
      }

      // 모든 언어의 자막을 한번에 가져오기
      const response = await fetch(`/api/subtitles?videoId=${videoId}`);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "자막 정보를 가져오는데 실패했습니다");
      }

      setVideoInfo(data.video);
      setLanguages(data.languages);
      setSubtitlesByLanguage(data.subtitles || {});

      // 첫 번째 언어 자동 선택
      if (data.languages && data.languages.length > 0) {
        setSelectedLanguage(data.languages[0].languageCode);
      }
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "알 수 없는 오류가 발생했습니다"
      );
    } finally {
      setLoading(false);
    }
  };

  const handleSelectLanguage = (languageCode: string) => {
    setSelectedLanguage(languageCode);
  };

  const formatTime = (seconds: number): string => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);
    const ms = Math.floor((seconds % 1) * 1000);

    if (hours > 0) {
      return `${hours.toString().padStart(2, "0")}:${minutes
        .toString()
        .padStart(2, "0")}:${secs.toString().padStart(2, "0")},${ms
        .toString()
        .padStart(3, "0")}`;
    }
    return `${minutes.toString().padStart(2, "0")}:${secs
      .toString()
      .padStart(2, "0")},${ms.toString().padStart(3, "0")}`;
  };

  return (
    <div className="min-h-screen bg-background p-4 sm:p-6 md:p-8">
      <div className="mx-auto max-w-4xl">
        <header className="mb-8 text-center">
          <h1 className="mb-2 text-4xl font-bold">YouTube Subtitle Editor</h1>
          <p className="text-muted-foreground">
            Extract, edit, and export subtitles with precision timing ✨
          </p>
        </header>

        {/* URL 입력 */}
        <div className="mb-8">
          <div className="flex gap-4">
            <input
              type="text"
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleLoadSubtitles();
                }
              }}
              placeholder="YouTube URL 또는 Video ID 입력"
              className="h-12 flex-1 rounded-lg border px-4 text-base"
              disabled={loading}
            />
            <button
              onClick={handleLoadSubtitles}
              disabled={loading || !url.trim()}
              className="h-12 rounded-lg bg-primary px-6 font-semibold text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-50"
            >
              {loading ? "로딩 중..." : "자막 불러오기"}
            </button>
          </div>
          {error && <p className="mt-2 text-sm text-destructive">{error}</p>}
        </div>

        {/* 비디오 정보 */}
        {videoInfo && (
          <div className="mb-6 rounded-lg border bg-card p-6">
            <h2 className="mb-2 text-xl font-semibold">{videoInfo.title}</h2>
            <div className="text-sm text-muted-foreground">
              <p>채널: {videoInfo.channelName}</p>
              <p>조회수: {videoInfo.viewCount.toLocaleString()}회</p>
              <p>영상 ID: {videoInfo.videoId}</p>
            </div>
          </div>
        )}

        {/* 자막 언어 목록 */}
        {languages.length > 0 && (
          <div className="mb-6">
            <h2 className="mb-4 text-xl font-semibold">
              사용 가능한 자막 언어 ({languages.length}개)
            </h2>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {languages.map((lang) => {
                const subtitleCount =
                  subtitlesByLanguage[lang.languageCode]?.length || 0;
                return (
                  <button
                    key={lang.languageCode}
                    onClick={() => handleSelectLanguage(lang.languageCode)}
                    disabled={loading}
                    className={`rounded-lg border p-4 text-left transition-colors ${
                      selectedLanguage === lang.languageCode
                        ? "border-primary bg-primary/10"
                        : "hover:bg-accent"
                    }`}
                  >
                    <div className="font-semibold">{lang.languageName}</div>
                    <div className="mt-1 flex gap-2 text-xs text-muted-foreground">
                      <span>{lang.languageCode}</span>
                      {subtitleCount > 0 && (
                        <span className="text-green-600">
                          {subtitleCount}개
                        </span>
                      )}
                      {lang.isAutoGenerated && (
                        <span className="text-yellow-600">자동 생성</span>
                      )}
                      {lang.isTranslatable && (
                        <span className="text-blue-600">번역 가능</span>
                      )}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* 자막 내용 */}
        {selectedLanguage &&
          subtitlesByLanguage[selectedLanguage] &&
          subtitlesByLanguage[selectedLanguage].length > 0 && (
            <div className="mb-6">
              <h2 className="mb-4 text-xl font-semibold">
                자막 내용 ({subtitlesByLanguage[selectedLanguage].length}개) -{" "}
                {
                  languages.find((l) => l.languageCode === selectedLanguage)
                    ?.languageName
                }
              </h2>
              <div className="max-h-[600px] overflow-y-auto rounded-lg border bg-card">
                <div className="divide-y">
                  {subtitlesByLanguage[selectedLanguage].map((subtitle) => (
                    <div
                      key={subtitle.index}
                      className="p-4 hover:bg-accent/50"
                    >
                      <div className="mb-1 text-xs text-muted-foreground">
                        {subtitle.index} | {formatTime(subtitle.startTime)} →{" "}
                        {formatTime(subtitle.endTime)} (
                        {(subtitle.endTime - subtitle.startTime).toFixed(2)}초)
                      </div>
                      <div className="text-sm">{subtitle.text}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

        {/* JSON 출력 (디버깅용) */}
        {selectedLanguage &&
          subtitlesByLanguage[selectedLanguage] &&
          subtitlesByLanguage[selectedLanguage].length > 0 && (
            <details className="mb-6">
              <summary className="cursor-pointer text-sm font-semibold">
                JSON 데이터 보기
              </summary>
              <pre className="mt-2 max-h-[400px] overflow-auto rounded-lg border bg-muted p-4 text-xs">
                {JSON.stringify(
                  {
                    videoInfo,
                    languages,
                    selectedLanguage,
                    subtitles: subtitlesByLanguage[selectedLanguage] || [],
                  },
                  null,
                  2
                )}
              </pre>
            </details>
          )}
      </div>
    </div>
  );
}
